defmodule Soonex.TagsIndexPage do
  @moduledoc false

  use Tableau.Page,
    layout: Soonex.RootLayout,
    permalink: "/tags",
    title: "Tags",
    page_kind: :tags_index,
    sitemap: %{priority: 0.5, changefreq: "weekly"}

  use Phoenix.Component
  use Corex

  def template(assigns) do
    tags = Map.get(assigns, :tags, %{})

    sorted =
      tags
      |> Map.to_list()
      |> Enum.sort_by(fn {_tag, posts} -> length(posts) end, :desc)

    assigns = Map.put(assigns, :sorted_tags, sorted)

    ~H"""
    <article class="flex min-h-dvh flex-col px-space py-size-xl">
      <div class="mx-auto flex w-full max-w-3xl flex-col gap-space-lg">
        <.navigate to="/" class="link link--accent w-fit">
          Back to home
        </.navigate>
        <header class="flex flex-col gap-space-sm border-b border-border pb-space-lg">
          <h1 class="m-0">Tags</h1>
          <p class="m-0 max-w-prose text-ink-muted">
            Every tag links to a static page generated by Tableau.TagExtension.
          </p>
        </header>
        <ul :if={@sorted_tags != []} class="m-0 flex list-none flex-col gap-space-sm p-0">
          <li :for={{tag, posts} <- @sorted_tags}>
            <.navigate to={tag.permalink} class="link link--accent">
              {tag.tag}
            </.navigate>
            <span class="text-ink-muted">
              {", #{length(posts)} #{if length(posts) == 1, do: "post", else: "posts"}"}
            </span>
          </li>
        </ul>
        <p :if={@sorted_tags == []} class="m-0 text-ink-muted">
          No tags yet. Add a <code class="rounded-md bg-layer px-1 py-0.5 text-sm">tags:</code>
          list to post front matter.
        </p>
      </div>
    </article>
    """
  end
end
